# Generated by Django 2.0.5 on 2018-05-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['district_name'],
            },
        ),
    ]
