# Generated by Django 2.0.5 on 2018-05-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdistrict_name', models.CharField(max_length=100)),
                ('subdistrict_code', models.CharField(max_length=3)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_district', to='core.District')),
            ],
            options={
                'verbose_name': 'Sub District',
                'ordering': ['district', 'subdistrict_name'],
            },
        ),
    ]
