# Generated by Django 2.0.5 on 2018-05-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('contractor_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_district', to='core.District')),
                ('contractor_subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_subdistrict', to='core.Subdistrict')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
