# Generated by Django 2.0.5 on 2018-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeworks_description', models.CharField(max_length=100)),
                ('typeworks_code', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Type of work',
                'ordering': ['typeworks_description'],
            },
        ),
    ]
