# Generated by Django 2.0.5 on 2018-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_typeworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundsource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundsource_description', models.CharField(max_length=100)),
                ('fundsource_code', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Fund of source',
                'ordering': ['fundsource_description'],
            },
        ),
    ]
