# Generated by Django 2.0.5 on 2018-05-16 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fundsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_description', models.CharField(max_length=200)),
                ('contract_year_cycle', models.IntegerField()),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contract_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contract_code', models.CharField(max_length=20)),
                ('contract_length_original', models.IntegerField()),
                ('contract_length_actual', models.IntegerField()),
                ('contract_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_district', to='core.District')),
                ('contract_subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_subdistrict', to='core.Subdistrict')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_id_contractor', to='core.Contractor')),
                ('fundsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_id_fundsource', to='core.Fundsource')),
                ('typeworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_id_typeworks', to='core.Typeworks')),
            ],
            options={
                'ordering': ['contractor'],
            },
        ),
    ]
